/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.campusforum.models


import com.google.gson.annotations.SerializedName
/**
 * 
 * @param text 
 * @param images 
 * @param title 
 */

data class ImageTextPostContent (
    @SerializedName("text")
    val text: kotlin.String,
    @SerializedName("images")
    val images: kotlin.Array<kotlin.String>,
    @SerializedName("title")
    val title: kotlin.String
)

