/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.campusforum.models


import com.google.gson.annotations.SerializedName
/**
 * 
 * @param newPassword 
 * @param oldPassword 
 */

data class InlineObject5 (
    @SerializedName("newPassword")
    val newPassword: kotlin.String,
    @SerializedName("oldPassword")
    val oldPassword: kotlin.String
)

