/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.campusforum.models

import com.example.campusforum.models.ImageTextPostContent

import com.google.gson.annotations.SerializedName
/**
 * 
 * @param type 
 * @param imageTextContent 
 * @param mediaContent 
 */

data class InlineObject1 (
    @SerializedName("type")
    val type: InlineObject1.Type,
    @SerializedName("imageTextContent")
    val imageTextContent: ImageTextPostContent? = null,
    @SerializedName("mediaContent")
    val mediaContent: kotlin.Array<kotlin.String>? = null
) {

    /**
    * 
    * Values: normal,audio,video
    */
    
    enum class Type(val value: kotlin.String){
        @SerializedName(value="normal")  normal("normal"),
        @SerializedName(value="audio")  audio("audio"),
        @SerializedName(value="video")  video("video");
    }
}

