/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.campusforum.models


import com.google.gson.annotations.SerializedName
/**
 * 
 * @param avatar URL只能以本站允许域名开头
 * @param nickname 
 * @param email 
 */

data class InlineObject (
    /* URL只能以本站允许域名开头 */
    @SerializedName("avatar")
    val avatar: kotlin.String,
    @SerializedName("nickname")
    val nickname: kotlin.String? = null,
    @SerializedName("email")
    val email: kotlin.String? = null
)

