/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.campusforum.models


import com.google.gson.annotations.SerializedName
/**
 * 
 * @param type 
 * @param commentId 对于评论被回复的情况，此字段为回复的id
 * @param uid 如给你点赞的人
 * @param notificationId 每个通知唯一
 * @param postId 推送通知和动态有关时存在
 */

data class WsPushNotification (
    @SerializedName("type")
    val type: WsPushNotification.Type,
    /* 对于评论被回复的情况，此字段为回复的id */
    @SerializedName("comment_id")
    val commentId: kotlin.String,
    /* 如给你点赞的人 */
    @SerializedName("uid")
    val uid: kotlin.String,
    /* 每个通知唯一 */
    @SerializedName("notification_id")
    val notificationId: kotlin.String,
    /* 推送通知和动态有关时存在 */
    @SerializedName("post_id")
    val postId: kotlin.String? = null
) {

    /**
    * 
    * Values: followingUpdated,postLiked,postCommented,commentLiked,commentReplied
    */
    
    enum class Type(val value: kotlin.String){
        @SerializedName(value="following_updated")  followingUpdated("following_updated"),
        @SerializedName(value="post_liked")  postLiked("post_liked"),
        @SerializedName(value="post_commented")  postCommented("post_commented"),
        @SerializedName(value="comment_liked")  commentLiked("comment_liked"),
        @SerializedName(value="comment_replied")  commentReplied("comment_replied");
    }
}

