/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package site.panda2134.thssforum.models


import com.google.gson.annotations.SerializedName
/**
 * 
 * @param token 在需要鉴权的接口，发送的HTTP请求都必须带Authorization头部，其值为  Bearer <token字符串>
 * @param uid 
 */

data class InlineResponse200 (
    /* 在需要鉴权的接口，发送的HTTP请求都必须带Authorization头部，其值为  Bearer <token字符串> */
    @SerializedName("token")
    val token: kotlin.String,
    @SerializedName("uid")
    val uid: kotlin.String
)

