/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package site.panda2134.thssforum.models

import com.google.gson.annotations.SerializedName

/**
 * 
 * @param type 
 * @param imageTextContent 
 * @param mediaContent 
 */

class ModifyPostRequest private constructor (
    @SerializedName("type")
    val type: PostType,
    @SerializedName("imageTextContent")
    val imageTextContent: ImageTextPostContent? = null,
    @SerializedName("mediaContent")
    val mediaContent: MediaPostContent? = null
) {
    companion object {
        fun makeImageTextPostModifyRequest(imageTextContent: ImageTextPostContent) =
            ModifyPostRequest(PostType.normal, imageTextContent = imageTextContent)
        fun makeAudioContent(mediaContent: MediaPostContent) =
            ModifyPostRequest(PostType.audio, mediaContent = mediaContent)
        fun makeVideoContent(mediaContent: MediaPostContent) =
            ModifyPostRequest(PostType.video, mediaContent = mediaContent)
    }
}

