/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package site.panda2134.thssforum.models


import com.google.gson.annotations.SerializedName
/**
 * 
 * @param count 
 */

data class NumOfLikesResponse(
    @SerializedName("count")
    val count: Int
)

data class LikeStatisticsResponse(
    @SerializedName("count")
    val count: Int,
    @SerializedName("likedByMe")
    val likedByMe: Boolean,
    @SerializedName("likes")
    val likesUidList: Array<String>
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as LikeStatisticsResponse

        if (count != other.count) return false
        if (likedByMe != other.likedByMe) return false
        if (!likesUidList.contentEquals(other.likesUidList)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = count
        result = 31 * result + likedByMe.hashCode()
        result = 31 * result + likesUidList.contentHashCode()
        return result
    }
}
