/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package site.panda2134.thssforum.models

import com.google.gson.annotations.SerializedName
/**
 * 
 * @param type 
 * @param id 字符串，新建动态时不发
 * @param by 字符串，新建时不发
 * @param location 
 * @param imageTextContent 
 * @param mediaContent 
 */

data class Post (
    @SerializedName("type")
    val type: Type,
    /* 字符串，新建动态时不发 */
    @SerializedName("id")
    val id: String? = null,
    /* 字符串，新建时不发 */
    @SerializedName("by")
    val by: String? = null,
    @SerializedName("location")
    val location: Location? = null,
    @SerializedName("imageTextContent")
    val imageTextContent: ImageTextPostContent? = null,
    @SerializedName("mediaContent")
    val mediaContent: MediaPostContent? = null
) {

    /**
    * 
    * Values: normal,audio,video
    */
    
    enum class Type(val value: String){
        @SerializedName(value="normal")  normal("normal"),
        @SerializedName(value="audio")  audio("audio"),
        @SerializedName(value="video")  video("video");
    }
}

