/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package site.panda2134.thssforum.models


import com.google.gson.annotations.SerializedName
/**
 * 
 * @param securityToken 
 * @param expiresAt rfc3339格式的日期
 * @param accessKeyId 
 * @param accessKeySecret 
 */

data class UploadTokenResponse (
    @SerializedName("securityToken")
    val securityToken: String,
    /* rfc3339格式的日期 */
    @SerializedName("expiresAt")
    val expiresAt: String,
    @SerializedName("accessKeyId")
    val accessKeyId: String,
    @SerializedName("accessKeySecret")
    val accessKeySecret: String
)

