/**
 * THSSForum
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package site.panda2134.thssforum.models


import com.google.gson.annotations.SerializedName
/**
 *
 * @param uid
 * @param nickname
 * @param email
 * @param avatar
 * @param intro
 */

data class User (
    @SerializedName("uid")
    val uid: String,
    @SerializedName("nickname")
    val nickname: String,
    @SerializedName("email")
    val email: String,
    @SerializedName("avatar")
    val avatar: String,
    @SerializedName("intro")
    val intro: String,
)