/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.campusforum.models


import com.google.gson.annotations.SerializedName
/**
 * 
 * @param nickname 
 * @param password 
 * @param email 
 */

data class InlineObject4 (
    @SerializedName("nickname")
    val nickname: kotlin.String,
    @SerializedName("password")
    val password: kotlin.String,
    @SerializedName("email")
    val email: kotlin.String
)

