/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param nickname 
 * @param password 
 * @param email 
 */

data class InlineObject (
    @Json(name = "nickname")
    val nickname: kotlin.String,
    @Json(name = "password")
    val password: kotlin.String,
    @Json(name = "email")
    val email: kotlin.String
)

