/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param token 
 * @param uniqueId 可以参考 https://devnote.pro/posts/10000002731155 获得android_id 作为此字段取值
 */

data class WsLoginRequest (
    @Json(name = "token")
    val token: kotlin.String,
    /* 可以参考 https://devnote.pro/posts/10000002731155 获得android_id 作为此字段取值 */
    @Json(name = "unique_id")
    val uniqueId: kotlin.String
)

