/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param text 
 * @param images 
 */

data class ImageTextPostContent (
    @Json(name = "text")
    val text: kotlin.String,
    @Json(name = "images")
    val images: kotlin.Array<kotlin.String>
)

