/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param avatar URL只能以本站允许域名开头
 * @param nickname 
 * @param email 
 */

data class InlineObject6 (
    /* URL只能以本站允许域名开头 */
    @Json(name = "avatar")
    val avatar: kotlin.String,
    @Json(name = "nickname")
    val nickname: kotlin.String? = null,
    @Json(name = "email")
    val email: kotlin.String? = null
)

