/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param commentId 
 * @param postId 
 */

data class InlineResponse2013 (
    @Json(name = "comment_id")
    val commentId: kotlin.String,
    @Json(name = "post_id")
    val postId: kotlin.String
)

