/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param description 比如“北京市海淀区清华大学中央主楼”
 * @param lon 
 * @param lat 
 */

data class Location (
    /* 比如“北京市海淀区清华大学中央主楼” */
    @Json(name = "description")
    val description: kotlin.String,
    @Json(name = "lon")
    val lon: java.math.BigDecimal,
    @Json(name = "lat")
    val lat: java.math.BigDecimal
)

