/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.ImageTextPostContent
import org.openapitools.client.models.Location
import org.openapitools.client.models.MediaPostContent

import com.squareup.moshi.Json
/**
 * 
 * @param type 
 * @param location 
 * @param id 字符串，新建动态时不发
 * @param by 字符串，新建时不发
 * @param imageTextContent 
 * @param mediaContent 
 */

data class Post (
    @Json(name = "type")
    val type: Post.Type,
    @Json(name = "location")
    val location: Location,
    /* 字符串，新建动态时不发 */
    @Json(name = "id")
    val id: kotlin.String? = null,
    /* 字符串，新建时不发 */
    @Json(name = "by")
    val by: kotlin.String? = null,
    @Json(name = "imageTextContent")
    val imageTextContent: ImageTextPostContent? = null,
    @Json(name = "mediaContent")
    val mediaContent: MediaPostContent? = null
) {

    /**
    * 
    * Values: normal,audio,video
    */
    
    enum class Type(val value: kotlin.String){
        @Json(name = "normal") normal("normal"),
        @Json(name = "audio") audio("audio"),
        @Json(name = "video") video("video");
    }
}

