/**
* THSSForum
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param type 
 * @param commentId 对于评论被回复的情况，此字段为回复的id
 * @param postId 推送通知和动态有关时存在
 */

data class WsPushNotification (
    @Json(name = "type")
    val type: WsPushNotification.Type,
    /* 对于评论被回复的情况，此字段为回复的id */
    @Json(name = "comment_id")
    val commentId: kotlin.String,
    /* 推送通知和动态有关时存在 */
    @Json(name = "post_id")
    val postId: kotlin.String? = null
) {

    /**
    * 
    * Values: followingUpdated,postLiked,postCommented,commentLiked,commentReplied
    */
    
    enum class Type(val value: kotlin.String){
        @Json(name = "following_updated") followingUpdated("following_updated"),
        @Json(name = "post_liked") postLiked("post_liked"),
        @Json(name = "post_commented") postCommented("post_commented"),
        @Json(name = "comment_liked") commentLiked("comment_liked"),
        @Json(name = "comment_replied") commentReplied("comment_replied");
    }
}

